### ISSUE TITLE
various error using the software

### ISSUE THREAD

**Issue by BletaJonatan** [JasonBrownDeveloper/ps3mca#1]
hey man, i know a lot of time has passed but here i am:
I tried using your tool with a 3rd party adapter and an official 8mb ps2 MC.
the adapter is a "MaX Pro" adapter, it also gets recognized by the ps3mca tool and by yours, it can READ and WRITE a ps1 memory card no problem with "PS1 MC Manager".
when using yours i downloaded the various libraries with pip but when running the "py .\ps3mca.py --test" command i got these errors:

PSps3mca-main> `py .\ps3mca.py --test`

Traceback (most recent call last):
  File "ps3mca-main\ps3mca.py", line 256, in <module>
    magic_gate()

  File "ps3mca-main\ps3mca.py", line 98, in magic_gate
    request_response("CS_AUTHORIZE")

  File "ps3mca-main\ps3mca.py", line 78, in request_response
    response = dev.read(0x81, wMaxPacketSize)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1029, in read
    ret = fn(
          ^^^

  File "Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 553, in bulk_read
    return self.__read(_lib.usb_bulk_read,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 692, in __read
    ret = int(_check(fn(
              ^^^^^^^^^^

  File "Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)

usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

since you made the program i can guess you know how the logic works right?

**Comment by BletaJonatan** [comment]
also if you could i would be glad if we could talk in private.

**Comment by JasonBrownDeveloper** [comment]
From the traceback, it appears that the USB device is not responding to the first read command issued.  To get that far in my script, pyUSB had to have been able to find and set the configuration for a USB device that reported being a ps3mca and then write to it.  I don't believe the device I tested with was a MaX Pro device, so it may need some special handling; different endpoint or different formatted command responses.
