### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by psxdev1** [JasonBrownDeveloper/ps3mca#2]
What do i include in python with pip ( e.g. libusb, libusbk etc.) I get a USB.core error about backend.

What os do you compile this on cause I use Windows and am trying to use pyinstaller  and trying to make a Windows exe it makes the exe but when i try to run the exe using the dump command i get the USB.core error

**Comment by extraweb1** [comment]
And what Windows driver are you using

**Comment by extraweb1** [comment]
here is my compile log


```
C:\Users\user1>pyinstaller --onefile I:\windows\PS3MCA-python\ps3mca-RetailKeys.py
328 INFO: PyInstaller: 6.1.0
328 INFO: Python: 3.12.0
359 INFO: Platform: Windows-10-10.0.19045-SP0
359 INFO: wrote C:\Users\user1\ps3mca-RetailKeys.spec
359 INFO: Extending PYTHONPATH with paths
['I:\\windows\\PS3MCA-python']
781 INFO: checking Analysis
781 INFO: Building Analysis because Analysis-00.toc is non existent
781 INFO: Initializing module dependency graph...
781 INFO: Caching module graph hooks...
796 INFO: Analyzing base_library.zip ...
2364 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
4668 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
5840 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
6434 INFO: Caching module dependency graph...
6606 INFO: Running Analysis Analysis-00.toc
6606 INFO: Looking for Python shared library...
6621 INFO: Using Python shared library: C:\Program Files\Python312\python312.dll
6621 INFO: Analyzing I:\windows\PS3MCA-python\ps3mca-RetailKeys.py
6684 INFO: Loading module hook 'hook-usb.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
6777 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\numpy\\_pyinstaller'...
7559 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
7824 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8043 INFO: Loading module hook 'hook-xml.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8949 INFO: Loading module hook 'hook-platform.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
8981 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
11996 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12184 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12324 INFO: Loading module hook 'hook-lxml.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12819 INFO: Loading module hook 'hook-nltk.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13757 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
16007 INFO: Loading module hook 'hook-regex.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
17022 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
19177 INFO: Processing module hooks...
19177 INFO: Loading module hook 'hook-lxml.etree.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
19349 INFO: Loading module hook 'hook-lxml.isoschematron.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
19396 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks'...
19396 INFO: checking Tree
19396 INFO: Building Tree because Tree-00.toc is non existent
19396 INFO: Building Tree Tree-00.toc
19474 INFO: checking Tree
19474 INFO: Building Tree because Tree-01.toc is non existent
19474 INFO: Building Tree Tree-01.toc
19474 INFO: checking Tree
19474 INFO: Building Tree because Tree-02.toc is non existent
19474 INFO: Building Tree Tree-02.toc
19474 INFO: Loading module hook 'hook-lxml.objectify.py' from 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
19740 INFO: Looking for ctypes DLLs
19802 INFO: Analyzing run-time hooks ...
19802 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
19802 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
19802 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
19818 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_nltk.py'
19818 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
19818 INFO: Including run-time hook 'C:\\Program Files\\Python312\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_usb.py'
19880 INFO: Looking for dynamic libraries
C:\Program Files\Python312\Lib\site-packages\PyInstaller\building\build_main.py:194: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
20950 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Program Files\\Python312\\Lib\\site-packages\\numpy.libs']
20950 INFO: Extra DLL search directories (PATH): []
21575 INFO: Warnings written to C:\Users\user1\build\ps3mca-RetailKeys\warn-ps3mca-RetailKeys.txt
21700 INFO: Graph cross-reference written to C:\Users\user1\build\ps3mca-RetailKeys\xref-ps3mca-RetailKeys.html
21778 INFO: checking PYZ
21778 INFO: Building PYZ because PYZ-00.toc is non existent
21778 INFO: Building PYZ (ZlibArchive) C:\Users\user1\build\ps3mca-RetailKeys\PYZ-00.pyz
23325 INFO: Building PYZ (ZlibArchive) C:\Users\user1\build\ps3mca-RetailKeys\PYZ-00.pyz completed successfully.
23387 INFO: checking PKG
23387 INFO: Building PKG because PKG-00.toc is non existent
23387 INFO: Building PKG (CArchive) ps3mca-RetailKeys.pkg
34387 INFO: Building PKG (CArchive) ps3mca-RetailKeys.pkg completed successfully.
34418 INFO: Bootloader C:\Program Files\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
34418 INFO: checking EXE
34419 INFO: Building EXE because EXE-00.toc is non existent
34419 INFO: Building EXE from EXE-00.toc
34420 INFO: Copying bootloader EXE to C:\Users\user1\dist\ps3mca-RetailKeys.exe
34789 INFO: Copying icon to EXE
35111 INFO: Copying 0 resources to EXE
35112 INFO: Embedding manifest in EXE
35295 INFO: Appending PKG archive to EXE
36186 INFO: Fixing EXE headers
42490 INFO: Building EXE from EXE-00.toc completed successfully.

C:\Users\user1>
```

**Comment by extraweb1** [comment]
this is the error when i run it

```
C:\Users\user1\dist>ps3mca-RetailKeys.exe -d ps2mem.bin
Traceback (most recent call last):
  File "ps3mca-RetailKeys.py", line 251, in <module>
  File "usb\core.py", line 1309, in find
usb.core.NoBackendError: No backend available
[5484] Failed to execute script 'ps3mca-RetailKeys' due to unhandled exception!

C:\Users\user1\dist>
```

**Comment by JasonBrownDeveloper** [comment]
https://pypi.org/project/pyusb/

https://pypi.org/project/pyDes/

Are the two third-party packages I used.  I developed this on an Ubuntu box I had, but it should work in Windows as well.
